### ISSUE TITLE
External links checker

### ISSUE THREAD

**Issue by lahwaacz** [lahwaacz/wiki-scripts#20]
Check external links and mark them with `{{Dead link}}`. Results should be cached to filter out temporarily unavailable services.

Useful reference, maybe it could be even reused:
https://en.wikipedia.org/wiki/User:Dispenser/Checklinks

**Comment by lahwaacz** [comment]
Common links to Arch sites should also be replaced with a dedicated template: Bug, AUR, Pkg

**Comment by kynikos** [comment]
Thank you for all your work, it doesn't go unnoticed even though I'm barely active in this period <3
