### ISSUE TITLE
toc.py: move rtl setting to table attribute

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#34]
Do you think it would make sense to move the rtl script setting from [L248](https://github.com/lahwaacz/wiki-scripts/blob/master/toc.py#L248) to a table attribute in the wiki docs, similar to what is done with `data-toc-alsoin`? ltr could be the default, and rtl mode would be used if the table has a `data-toc-rtl="1"` attribute.

**Comment by lahwaacz** [comment]
I'm not sure, after all it's a feature of the language, not the table. Perhaps moving it to `ws.ArchWiki.lang` instead would be better?

**Comment by kynikos** [comment]
Yep, `ws.ArchWiki.lang` looks appropriate to me too, anyway of course the decision is ultimately up to you, it's just that storing that info in `toc.py` seems a bit out of place to me, but nothing too important after all.

**Comment by lahwaacz** [comment]
Of course you're completely right that it was out of place in `toc.py`, thanks for pointing it out. There are most likely many similar inconsistencies waiting to be revealed :wink:
