### ISSUE TITLE
statistics: fix user counts in table intro

### ISSUE THREAD

**Issue by lahwaacz** [lahwaacz/wiki-scripts#4]
The user counts may not be correct in some cases, e.g. [here](https://wiki.archlinux.org/index.php?title=User:Lahwaacz/Statistics&oldid=359457) the table shows less than 70 users with more than 50 recent edits as claimed in the intro.

**Comment by kynikos** [comment]
Uh true... Setting the minimum number of recent changes is one of the last features that I introduced, certainly after showing the counts in the intro: the count of the users with more than N recent edits was — and still is — assuming that N==1, i.e. the count is only broken when N!=1.
Now, unfortunately I can't think of any elegant ways to fix this bug: if we want to keep the counts (i.e. not drop them nor only show them when N==1), I'm afraid we have to increment a counter after https://github.com/lahwaacz/wiki-scripts/blob/3520a81ac354ab331ecf9917a93d5bb698b85074/statistics.py#L311 with an additional `if recenteditcount >= self.MINRECEDITS:`.
