### ISSUE TITLE
Multiple modes for revision content synchronization

### ISSUE THREAD

**Issue by lahwaacz** [lahwaacz/wiki-scripts#48]
Allow syncing content independently from revisions. Metadata of all revisions have to be always synced, but the content does not have to be. There should be at least these modes:

- [x] full synchronization
- [x] latest revision synchronization ~(and fetch the remaining content on-demand)~
- ~none (on-demand) synchronization~

**Comment by lahwaacz** [comment]
@kynikos Now we can run `checkdb.py --content-sync-mode all` to synchronize all content from the wiki for backup :wink: 

The script also runs some checks if the overall synchronization is consistent with the remote wiki, please let me know if it reports some differences. Some of them are "expected" though, e.g. differences in the recentchanges table are unimportant (and I have no idea why they actually happen...)

**Comment by kynikos** [comment]
Oooh you know I love wiki backups, thank you!
I should have redirected it to some file though, it did return lots (at a glance) of differences, I'll try again in the weekend :)

**Comment by kynikos** [comment]
Oops today this happens on 16d23938ed2682a560bd32b8057b753a4d5a19b8:

```
% python checkdb.py --content-sync-mode all
INFO     No new changes since the last database synchronization.
INFO     Fetched revids 443941-443971.
INFO     Synchronization of all revisions content for 31 pages took 6.53 seconds.
Checking individual titles...
Traceback (most recent call last):
  File "checkdb.py", line 645, in <module>
    check_specific_titles(api, db)
  File "checkdb.py", line 138, in check_specific_titles
    assert api_title.context == db_title.context
AssertionError
```

**Comment by lahwaacz** [comment]
Yep, that happens since yesterday due to MW 1.34... https://github.com/lahwaacz/wiki-scripts/commit/7a1055bd6f81a8f60543f8d9cde1f2738bc66032 was also due to MW 1.34 and there is still at least one compatibility issue remaining, then there is one issue regarding the synchronization of the DeveloperWiki pages. Do you have a backup of the database from before the migration? It might be easiest to restore it and synchronize again with a fixed code...

**Comment by lahwaacz** [comment]
The problem with title contexts should be fixed by https://github.com/lahwaacz/wiki-scripts/commit/8f5f1c45a9fbf2b811c6f1db2539d25d0655d2ff - please run the alembic migration with `alembic upgrade head` and try `checkdb.py` again :wink:

**Comment by lahwaacz** [comment]
All issues with the synchronization of DeveloperWiki pages should be fixed now, except for one unimportant difference in the `recentchanges` table.

**Comment by kynikos** [comment]
Yay, the synchronization worked fine this time! I restored a dump from 29/2 (if you need it I can share).
However, back to the original plan to report the differences, it output 30MB of them most/all quite clearly due to some sorting problems again ^^ Do you want a sample?

**Comment by lahwaacz** [comment]
I made a backup just before the migration, so I'm good. If you can share the output of differences, that would be great!

**Comment by kynikos** [comment]
Oh here you go: https://drive.google.com/file/d/16M56CrVuzwvyBe8kh8UGEhtjX_j7cb69/view?usp=sharing

**Comment by lahwaacz** [comment]
Thanks, most of it was easy (two differences in the recentchanges table which are expected/unsolvable, then most of the file was due to different sorting of the lists of users). Then there are some items from the archive table where your database does not have the right values for `ar_deleted` (which is the "commenthidden", "sha1hidden" and "userhidden" fields in the API) - no idea how that happened, since you can access the archive you should also be able to access these fields... At the bottom you can see that the revisions for the DeveloperWiki pages which I manually restored and archived before the migration stayed in the archive table, which is probably a corner case that the synchronization does not cover. I don't know how to solve it, maybe just delete them from the archive table manually... (The revision table is OK according to the script, so the items should already be there.)

**Comment by kynikos** [comment]
Nice, the log is down to 43K now! Still a little too long to parse with my eyes though, I trust you when you say things are under control, anyway it's here if you want to inspect it: https://drive.google.com/file/d/1J8I4UR0ue0WpyXf6woGxEbfaW0N_NwpX/view?usp=sharing
