### ISSUE TITLE
toc.py: Infinite loop

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#55]
Hi, today `toc.py` [87906c8](https://github.com/lahwaacz/wiki-scripts/blob/87906c84bc10df398d3d31fb8f100067c8a186e4/toc.py) is infinite-looping at:

https://github.com/lahwaacz/wiki-scripts/blob/87906c84bc10df398d3d31fb8f100067c8a186e4/toc.py#L340

On [Table of contents (Русский) rev:556320](https://wiki.archlinux.org/index.php?title=Table_of_contents_%28%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9%29&oldid=556320). I'm not sure how the language comparison feature works, I thought it would be much quicker for you to investigate, cheers.

**Comment by lahwaacz** [comment]
Thanks, it should be fixed now.
