### ISSUE TITLE
ExtlinkReplacements: replace irc:// with ircs://

### ISSUE THREAD

**Issue by nl6720** [lahwaacz/wiki-scripts#75]
Similar to the `http://`  → `https://` replacement, `irc://` could be updated to `ircs://` for networks that support it.

Some of the networks that support IRC over TLS (and have a valid certificate) are:
* `chat.freenode.net`
* `irc.oftc.net`
* `irc.rizon.net`
* `irc.azzurra.org`

**Comment by lahwaacz** [comment]
Is it possible for us to also check if the `irc://`/`ircs://` links are working? Can we use some generic networking library or do we need an actual IRC client? There are likely some Python libraries that we could use...

**Comment by nl6720** [comment]
I'm sure it' should be _possible_, but is it worth it...
For `ircs://` you would also need to make sure the python lib validates the certificate (if it is trusted and also valid for the server).
