### ISSUE TITLE
statistics.py: Remove "Staff" badge?

### ISSUE THREAD

**Issue by kynikos** [lahwaacz/wiki-scripts#85]
See https://wiki.archlinux.org/index.php?title=ArchWiki:Statistics&diff=prev&oldid=702544

I don't think I have to explain much, sorry I don't have time rn to work on a patch :)

**Comment by lahwaacz** [comment]
Thanks for noticing it, we've patched it in https://wiki.archlinux.org/title/Special:UserRights/Alad :wink:
